### PR TITLE
Update WDSP to version 1.20

### PR DESCRIPTION
**Pull request by dl1ycf**
There are several changes in the "WDSP" files which simply reflect the update from 1.18 to 1.20. There is no very little (much less than before) difference between these files and those on the master WDSP repo (TAPR/Thetis).
There is a major change to wdsp.h since it is now largely machine generated, using the program "make_interface" (source code added as well). This ensures consistency and was necessary because upon the WDSP 1.18 ==> 1.20 update , the interface of "create_analyzer" changed and I wanted to be sure *all* interfaces in wdsp.h are correct. As a side effect, wdsp.h now *does* include all interfaces.

The WDSP guide (PDF file) has also been replaced by the 1.20 version.

If the aim is to have as little difference between the "Unix" and "Windows" versions of WDSP, this PR is the way to go.

### CODE REVIEW

**Comment by howard0su** [comment]
One issue I noticed in the new way to expose functions: We didn't expose enum values. For example, SetRXAMode (int channel, int mode); we don't have mode def in wdsp.h.

**Comment by dl1ycf** [comment]
The definition in wdsp is consistent with the definition in RXA.c

RXA.c:void SetRXAMode (int channel, int mode)

 (in fact,
it is machine generated therefrom), and also consistent with the
definition in RXA.h

RXA.h:extern __declspec (dllexport) void SetRXAMode (int channel, int mode);

But you are right, the mode enum is not exported so one relies on having
a compatible definition in the SDR program. This is done in piHPSDR and
linHPSDR, where there are #defines or an enum which has to match the
internal definition in wdsp, and the same is done in Thetis (see file enums.cs).

So you are right, there is a "software engineering issue". Should WDSP change
the enum, all the programs mentiones "go into the bush".

Note that this is not specific to this PR, it is how WDSP works.

**Comment by howard0su** [comment]
Completely agree. I am not sure where is the forum for this type of discussion. I vote to use enum in header file and expose the related enum into wdsp.h.

**Comment by dl1ycf** [comment]
You have to complain "upstream". At this place, this is the Linux/MacOS/Android adaptation of WDSP
which is kept as close as possible to the original (Windows?) version, to make life easier when
merging-in future updates.

The problem you mention most likely affecty all "clients" of this library, I checked the "Thetis"
source code this morning.

Yours,

Christoph DL1YCF.

**Comment by dl1ycf** [comment]
I think after several months, I close the PR and re-open it once I see more activity.

**Pull request closed without merging**
